packaging_format = 2

id = "lemmy"
name = "Lemmy"
description.en = "Link aggregator/Reddit clone for the fediverse"
description.fr = "Agrégateur de liens/clone Reddit pour le fedivers"

version = "0.16.7~ynh1"

maintainers = []

[upstream]
license = "GPL-3.0"
website = "https://join-lemmy.org/"
demo = "https://lemmy.ml/"
admindoc = "https://join-lemmy.org/docs/en/"
code = "https://github.com/LemmyNet/lemmy"

[integration]
yunohost = ">= 11.1.19"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

    [install.domain]
    type = "domain"
    full_domain = true

[resources]
    [resources.sources]
        [resources.sources.docker-image-extract]
        url = "https://codeload.github.com/jjlin/docker-image-extract/tar.gz/b664b29a1de37d25f732e885e1331a8e90f67dcd"
        sha256 = "7b2c8baeec6e9a67c905d4d55e4dc0944815cf55bd6bf11fadbb6eb8990b4912"

        [resources.sources.lemmy-translations]
        url = "https://codeload.github.com/LemmyNet/lemmy-translations/tar.gz/ddf0d3a4dcfba5eddbcdb702db2470b52abb3815"
        sha256 = "7df72cdba8a6c23c9dca528d3fd71dce13f5263b7a59c8512253364d94797757"

    [resources.ports]
    main.default = 8536
    ui.default = 8537

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["pictrs-data"]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "postgresql espeak"

    [resources.database]
    type = "postgresql"
